import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const dist = path.join(root, "dist");
const origin = "https://avaru-spices-surkhet.surkhettimes05.chatgpt.site";

const wa = {
  tester: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%27m%20interested%20in%20joining%20the%20Momo%20Achar%20Masala%20product%20testing%20in%20Birendranagar.",
  retailer: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%27m%20a%20retailer%20interested%20in%20discussing%20Avaru%20products.",
  general: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%20have%20a%20general%20enquiry."
};

const copy = {
  en: {
    lang: "en", prefix: "", switchLabel: "नेपाली", switchPrefix: "/ne",
    nav: [["Home", "/"], ["About", "/about/"], ["Our masalas", "/products/"], ["Product testing", "/testing/"], ["Contact", "/contact/"]],
    footer: "Masalas and spice blends for Nepali kitchens.", location: "Testing in Birendranagar, Surkhet, Nepal",
    private: "Private preview — product and commercial details are still being finalised.",
    menu: "Menu", close: "Close menu", skip: "Skip to content"
  },
  ne: {
    lang: "ne", prefix: "/ne", switchLabel: "English", switchPrefix: "",
    nav: [["गृहपृष्ठ", "/ne/"], ["हाम्रो बारेमा", "/ne/about/"], ["हाम्रा मसला", "/ne/products/"], ["उत्पादन परीक्षण", "/ne/testing/"], ["सम्पर्क", "/ne/contact/"]],
    footer: "नेपाली भान्साका लागि मसला र मसलाका मिश्रण।", location: "वीरेन्द्रनगर, सुर्खेत, नेपालमा परीक्षण हुँदैछ",
    private: "निजी पूर्वावलोकन — उत्पादन र व्यापारसम्बन्धी विवरण अझै अन्तिम हुँदैछन्।",
    menu: "मेनु", close: "मेनु बन्द गर्नुहोस्", skip: "मुख्य सामग्रीमा जानुहोस्"
  }
};

const pages = {
  en: [
    { slug: "", key: "home", title: "Avaru | Masalas for Nepali kitchens", desc: "Meet Avaru, a masala and spices brand being developed in Birendranagar, Nepal. Learn about Momo Achar Masala and join product testing.", h1: "Masalas for the food we share.", eyebrow: "From Birendranagar, for Nepali kitchens", body: `
      <section class="hero wrap"><div class="hero-copy"><p class="eyebrow">From Birendranagar, for Nepali kitchens</p><h1>Masalas for the food we share.</h1><p class="lede">Avaru is developing spice blends for Nepali home cooks. Our first product in testing is a dry masala made to help you prepare tomato-and-timur momo dipping achar.</p><div class="actions"><a class="button" href="/testing/">Join product testing <span aria-hidden="true">↗</span></a><a class="text-link" href="/products/momo-achar-masala/">Meet the first product</a></div><p class="micro">Recipe, pack size, price and launch timing are not final.</p></div><figure class="hero-media"><img src="/assets/momo-hero.webp" width="1536" height="1024" alt="Steamed momo served beside a separate bowl of tomato-and-timur dipping achar"><figcaption>The finished dipping achar is prepared separately and served with momo.</figcaption></figure></section>
      <section class="clarity"><div class="wrap narrow"><p class="eyebrow">One useful distinction</p><h2>Momo achar is the sauce.<br>Momo achar masala helps you make it.</h2><p>Avaru Momo Achar Masala is a <strong>dry spice blend</strong>. It is not a ready-to-eat achar, and it is not used in momo filling.</p></div></section>
      <section class="process wrap"><div class="section-head"><p class="eyebrow">What the product does</p><h2>From dry blend to the bowl</h2></div><ol class="steps"><li><span>01</span><strong>Dry masala</strong><p>The product being tested: a measured spice blend.</p></li><li><span>02</span><strong>Prepare your achar</strong><p>Combine it as part of a tomato-and-timur momo achar recipe. The final method is still being tested.</p></li><li><span>03</span><strong>Serve and share</strong><p>A finished dipping achar you feel happy to put beside your momo.</p></li></ol></section>
      <section class="product-feature wrap"><div><p class="eyebrow">First blend in testing</p><h2>Avaru Momo Achar Masala</h2><p>Made for home cooks who want a clearer starting point when preparing momo dipping achar. Testing will shape the final recipe and instructions.</p><a class="text-link" href="/products/momo-achar-masala/">See what is confirmed</a></div><div class="status-card"><span class="status">Product testing</span><h3>Help shape what comes next</h3><p>We are inviting relevant home cooks in and around Birendranagar to share practical feedback.</p><a class="button button-dark" href="${wa.tester}" target="_blank" rel="noopener">Ask to join on WhatsApp</a></div></section>` },
    { slug: "about", key: "about", title: "About Avaru | Avaru Masalas", desc: "Learn about Avaru, a masala and spices brand being developed for Nepali kitchens in Birendranagar, Surkhet.", h1: "A spice brand taking shape in Surkhet.", eyebrow: "About Avaru", body: `<section class="page-hero wrap narrow"><p class="eyebrow">About Avaru</p><h1>A spice brand taking shape in Surkhet.</h1><p class="lede">Avaru is being developed in Birendranagar with a simple purpose: to make useful masalas and spice blends for the foods Nepali kitchens already love to prepare and share.</p></section><section class="split wrap"><div><h2>Starting with a real kitchen task</h2><p>Our first product in testing focuses on momo achar—not the momo filling, and not a ready-made sauce. Avaru Momo Achar Masala is a dry blend intended to be used while preparing tomato-and-timur dipping achar.</p></div><div><h2>Listening before launching</h2><p>The recipe, instructions, pack size, price, availability and launch date are still being finalised. Feedback from home cooks and conversations with retailers will help us make responsible decisions.</p></div></section><section class="banner"><div class="wrap"><p class="eyebrow">Where we are now</p><h2>Testing in Birendranagar, Surkhet</h2><p>We are focused on learning what works in real kitchens before making commercial promises.</p><a class="button button-light" href="/testing/">Join the trial</a></div></section>` },
    { slug: "products", key: "products", title: "Our Masalas | Avaru", desc: "Explore Avaru masalas in development, beginning with a dry blend for tomato-and-timur momo dipping achar.", h1: "Our masalas begin with one careful blend.", eyebrow: "Our masalas", body: `<section class="page-hero wrap narrow"><p class="eyebrow">Our masalas</p><h1>Our masalas begin with one careful blend.</h1><p class="lede">Avaru is a broader masala and spices brand for Nepali kitchens. Today, one product is in testing. We will only introduce future blends when they are approved.</p></section><section class="product-card wrap"><div class="product-art"><span class="product-type">Dry spice blend</span><div class="bowl-mark" aria-hidden="true">अ</div></div><div><span class="status">In testing</span><h2>Momo Achar Masala</h2><p>A dry blend used while preparing tomato-and-timur momo dipping achar. It is neither a ready-made sauce nor a momo filling masala.</p><ul class="checklist"><li>Designed for the dipping achar served with momo</li><li>Final recipe and preparation method are still under test</li><li>No approved price, pack size or launch date yet</li></ul><a class="button" href="/products/momo-achar-masala/">View product details</a></div></section>` },
    { slug: "products/momo-achar-masala", key: "product", title: "Momo Achar Masala | Avaru", desc: "Avaru Momo Achar Masala is a dry spice blend being tested for preparing tomato-and-timur momo dipping achar in Birendranagar, Nepal.", h1: "Momo Achar Masala, explained simply.", eyebrow: "First product in testing", body: `<section class="page-hero wrap narrow"><p class="eyebrow">First product in testing</p><h1>Momo Achar Masala, explained simply.</h1><p class="lede">It is a dry spice blend used as part of making tomato-and-timur momo dipping achar—the sauce served beside momo.</p><div class="actions"><a class="button" href="${wa.tester}" target="_blank" rel="noopener">Ask to join testing</a><a class="text-link" href="#questions">Read common questions</a></div></section><section class="process wrap"><div class="section-head"><p class="eyebrow">The distinction</p><h2>Dry masala → preparation → dipping achar</h2></div><ol class="steps"><li><span>01</span><strong>Momo achar masala</strong><p>A dry spice blend. This is the Avaru product being tested.</p></li><li><span>02</span><strong>Preparation</strong><p>Use the blend as part of preparing a tomato-and-timur achar. The final method is not yet approved.</p></li><li><span>03</span><strong>Momo achar</strong><p>The finished dipping sauce served with momo. This is not what is sold in the pouch.</p></li></ol></section><section class="facts wrap"><div><p class="eyebrow">Confirmed today</p><h2>Clear facts, without guesses</h2></div><dl><div><dt>Product type</dt><dd>Dry spice blend</dd></div><div><dt>Intended use</dt><dd>Preparing tomato-and-timur momo dipping achar</dd></div><div><dt>Testing location</dt><dd>Birendranagar, Surkhet, Nepal</dd></div><div><dt>Still being finalised</dt><dd>Recipe, method, pack size, price, availability and launch date</dd></div></dl></section><section class="faq wrap narrow" id="questions"><p class="eyebrow">Common questions</p><h2>Answers without the extra spice</h2><details open><summary>What is momo achar masala?</summary><p>It is a dry spice blend used while making the tomato-and-timur dipping achar served with momo.</p></details><details><summary>Is it a ready-made achar?</summary><p>No. The masala is an ingredient for preparing the achar; it is not a ready-to-eat sauce.</p></details><details><summary>Is it used in momo filling?</summary><p>No. It is intended for momo dipping achar, not the filling inside momo.</p></details><details><summary>Can I buy it now?</summary><p>Commercial details are not approved yet. The product is currently being tested in Birendranagar.</p></details><details><summary>How can I join testing?</summary><p>Send Avaru a WhatsApp message. We will let you know whether the current testing round is relevant to you.</p></details></section>` },
    { slug: "testing", key: "testing", title: "Join Product Testing | Avaru", desc: "Interested in testing Avaru Momo Achar Masala in Birendranagar? Contact Avaru on WhatsApp to share your interest.", h1: "Cook. Taste. Tell us what worked.", eyebrow: "Join the trial", body: `<section class="page-hero wrap narrow"><p class="eyebrow">Join the trial</p><h1>Cook. Taste. Tell us what worked.</h1><p class="lede">We are inviting relevant home cooks in and around Birendranagar to help us test Avaru Momo Achar Masala before commercial details are final.</p></section><section class="testing-grid wrap"><div><h2>What testing means</h2><ol class="number-list"><li><span>1</span><p><strong>Tell us you are interested.</strong><br>Start a short WhatsApp conversation using the button below.</p></li><li><span>2</span><p><strong>We confirm the fit.</strong><br>Testing opportunities may depend on location and the current stage of the trial.</p></li><li><span>3</span><p><strong>You prepare and share feedback.</strong><br>We want honest notes about clarity, preparation and the result you would serve.</p></li></ol></div><aside class="contact-card"><p class="eyebrow">Start on WhatsApp</p><h2>Interested in testing?</h2><p>The link opens a prefilled message. WhatsApp will share your phone number and any information you choose to send directly with Avaru.</p><a class="button button-dark" href="${wa.tester}" target="_blank" rel="noopener">Message Avaru</a><p class="micro">No website form or hidden data collection.</p></aside></section>` },
    { slug: "contact", key: "contact", title: "Contact Avaru | Testing and Retailer Enquiries", desc: "Contact Avaru on WhatsApp for product testing, retailer conversations or general questions in Birendranagar, Surkhet.", h1: "One number, three clear conversations.", eyebrow: "Contact Avaru", body: `<section class="page-hero wrap narrow"><p class="eyebrow">Contact Avaru</p><h1>One number, three clear conversations.</h1><p class="lede">Choose the reason for your message and WhatsApp will open with the right introduction. We are currently testing in Birendranagar, Surkhet, Nepal.</p></section><section class="contact-options wrap"><article><span>01</span><h2>Home cooks</h2><p>Ask about taking part in Momo Achar Masala testing.</p><a class="text-link" href="${wa.tester}" target="_blank" rel="noopener">Join product testing</a></article><article><span>02</span><h2>Retailers</h2><p>Start a conversation about future stocking possibilities. Availability is not yet confirmed.</p><a class="text-link" href="${wa.retailer}" target="_blank" rel="noopener">Make a retailer enquiry</a></article><article><span>03</span><h2>General questions</h2><p>Ask something else about Avaru or the product in testing.</p><a class="text-link" href="${wa.general}" target="_blank" rel="noopener">Send a general enquiry</a></article></section><section class="banner"><div class="wrap"><p class="eyebrow">WhatsApp</p><h2>+977 9822403262</h2><p>We have not published an office address, email address or opening hours.</p></div></section>` }
  ],
  ne: [
    { slug: "", key: "home", title: "Avaru | नेपाली भान्साका लागि मसला", desc: "अवरु वीरेन्द्रनगरमा विकास हुँदै गरेको नेपाली मसला ब्रान्ड हो। मोमो अचार मसला र उत्पादन परीक्षणबारे जान्नुहोस्।", h1: "सँगै बाँडेर खाने परिकारका लागि मसला।", eyebrow: "वीरेन्द्रनगरबाट, नेपाली भान्साका लागि", body: `<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">वीरेन्द्रनगरबाट, नेपाली भान्साका लागि</p><h1>सँगै बाँडेर खाने परिकारका लागि मसला।</h1><p class="lede">अवरुले नेपाली घरका भान्साका लागि मसलाका मिश्रण विकास गर्दैछ। परीक्षणमा रहेको हाम्रो पहिलो उत्पादन गोलभेँडा र टिमुरको मोमो डुबाउने अचार बनाउन प्रयोग गरिने सुक्खा मसला हो।</p><div class="actions"><a class="button" href="/ne/testing/">उत्पादन परीक्षणमा सहभागी हुनुहोस् <span aria-hidden="true">↗</span></a><a class="text-link" href="/ne/products/momo-achar-masala/">पहिलो उत्पादन हेर्नुहोस्</a></div><p class="micro">रेसिपी, प्याकको आकार, मूल्य र सार्वजनिक हुने समय अन्तिम भएका छैनन्।</p></div><figure class="hero-media"><img src="/assets/momo-hero.webp" width="1536" height="1024" alt="छुट्टै कचौरामा गोलभेँडा र टिमुरको अचारसँग राखिएको बफाएको मोमो"><figcaption>तयार अचार अलग्गै बनाइन्छ र मोमोसँग डुबाएर खान दिइन्छ।</figcaption></figure></section><section class="clarity"><div class="wrap narrow"><p class="eyebrow">एउटा महत्त्वपूर्ण भिन्नता</p><h2>मोमो अचार भनेको तयार सस हो।<br>मोमो अचार मसालाले त्यो बनाउन मद्दत गर्छ।</h2><p>अवरु मोमो अचार मसाला एउटा <strong>सुक्खा मसलाको मिश्रण</strong> हो। यो खान तयार अचार होइन र मोमोको भित्रको भराइमा प्रयोग हुने मसला पनि होइन।</p></div></section><section class="process wrap"><div class="section-head"><p class="eyebrow">उत्पादनले के गर्छ</p><h2>सुक्खा मिश्रणदेखि कचौरासम्म</h2></div><ol class="steps"><li><span>०१</span><strong>सुक्खा मसला</strong><p>परीक्षण भइरहेको उत्पादन: नापेर मिलाइएको मसलाको मिश्रण।</p></li><li><span>०२</span><strong>आफ्नो अचार बनाउनुहोस्</strong><p>गोलभेँडा र टिमुरको मोमो अचार बनाउँदा यसलाई प्रयोग गरिन्छ। अन्तिम विधि परीक्षणमै छ।</p></li><li><span>०३</span><strong>पस्कनुहोस् र बाँड्नुहोस्</strong><p>मोमोसँग दिन आफू सन्तुष्ट हुने तयार डुबाउने अचार।</p></li></ol></section><section class="product-feature wrap"><div><p class="eyebrow">परीक्षणमा रहेको पहिलो मिश्रण</p><h2>अवरु मोमो अचार मसाला</h2><p>मोमोको डुबाउने अचार बनाउँदा स्पष्ट सुरुवात चाहने घरका भान्सेहरूका लागि। परीक्षणबाट अन्तिम रेसिपी र निर्देशन तयार गर्न सहयोग हुनेछ।</p><a class="text-link" href="/ne/products/momo-achar-masala/">पक्का भएका कुरा हेर्नुहोस्</a></div><div class="status-card"><span class="status">उत्पादन परीक्षण</span><h3>अबको उत्पादन बनाउन सहयोग गर्नुहोस्</h3><p>वीरेन्द्रनगर र वरपरका इच्छुक घरका भान्सेबाट व्यवहारिक प्रतिक्रिया खोजिरहेका छौँ।</p><a class="button button-dark" href="${wa.tester}" target="_blank" rel="noopener">WhatsApp मा सोध्नुहोस्</a></div></section>` },
    { slug: "about", key: "about", title: "अवरुबारे | अवरु मसला", desc: "वीरेन्द्रनगर, सुर्खेतमा नेपाली भान्साका लागि विकास हुँदै गरेको मसला ब्रान्ड अवरुबारे जान्नुहोस्।", h1: "सुर्खेतमा आकार लिँदै गरेको मसला ब्रान्ड।", eyebrow: "अवरुबारे", body: `<section class="page-hero wrap narrow"><p class="eyebrow">अवरुबारे</p><h1>सुर्खेतमा आकार लिँदै गरेको मसला ब्रान्ड।</h1><p class="lede">अवरु वीरेन्द्रनगरमा एउटा सरल उद्देश्यसहित विकास हुँदैछ—नेपाली भान्साले पकाउन र बाँड्न मन पराउने परिकारका लागि उपयोगी मसला बनाउने।</p></section><section class="split wrap"><div><h2>भान्साको वास्तविक कामबाट सुरुवात</h2><p>हाम्रो पहिलो परीक्षण मोमो अचारमा केन्द्रित छ—मोमोको भराइमा होइन र खान तयार ससमा पनि होइन। अवरु मोमो अचार मसाला गोलभेँडा र टिमुरको डुबाउने अचार बनाउँदा प्रयोग गरिने सुक्खा मिश्रण हो।</p></div><div><h2>सार्वजनिक गर्नुअघि सुन्दै</h2><p>रेसिपी, निर्देशन, प्याकको आकार, मूल्य, उपलब्धता र सार्वजनिक हुने मिति अझै अन्तिम हुँदैछन्। घरका भान्सेको प्रतिक्रिया र खुद्रा विक्रेतासँगको कुराकानीले जिम्मेवार निर्णय गर्न मद्दत गर्छ।</p></div></section><section class="banner"><div class="wrap"><p class="eyebrow">अहिलेको अवस्था</p><h2>वीरेन्द्रनगर, सुर्खेतमा परीक्षण</h2><p>व्यापारिक वाचा गर्नुअघि वास्तविक भान्सामा के काम गर्छ भन्ने बुझ्दैछौँ।</p><a class="button button-light" href="/ne/testing/">परीक्षणमा सहभागी हुनुहोस्</a></div></section>` },
    { slug: "products", key: "products", title: "हाम्रा मसला | अवरु", desc: "अवरुले विकास गर्दै गरेका मसला हेर्नुहोस्, सुरुमा गोलभेँडा र टिमुरको मोमो डुबाउने अचारका लागि सुक्खा मिश्रण।", h1: "हाम्रा मसला एउटा ध्यानपूर्वक बनाइएको मिश्रणबाट सुरु हुन्छन्।", eyebrow: "हाम्रा मसला", body: `<section class="page-hero wrap narrow"><p class="eyebrow">हाम्रा मसला</p><h1>हाम्रा मसला एउटा ध्यानपूर्वक बनाइएको मिश्रणबाट सुरु हुन्छन्।</h1><p class="lede">अवरु नेपाली भान्साका लागि फराकिलो मसला ब्रान्ड हो। अहिले एउटा उत्पादन परीक्षणमा छ। भविष्यका मिश्रण स्वीकृत भएपछि मात्र प्रस्तुत गर्नेछौँ।</p></section><section class="product-card wrap"><div class="product-art"><span class="product-type">सुक्खा मसलाको मिश्रण</span><div class="bowl-mark" aria-hidden="true">अ</div></div><div><span class="status">परीक्षणमा</span><h2>मोमो अचार मसाला</h2><p>गोलभेँडा र टिमुरको मोमो डुबाउने अचार बनाउँदा प्रयोग गरिने सुक्खा मिश्रण। यो खान तयार सस वा मोमोको भराइमा हाल्ने मसला होइन।</p><ul class="checklist"><li>मोमोसँग दिइने डुबाउने अचारका लागि</li><li>अन्तिम रेसिपी र बनाउने विधि परीक्षणमै छन्</li><li>स्वीकृत मूल्य, प्याकको आकार वा सार्वजनिक हुने मिति छैन</li></ul><a class="button" href="/ne/products/momo-achar-masala/">उत्पादन विवरण हेर्नुहोस्</a></div></section>` },
    { slug: "products/momo-achar-masala", key: "product", title: "मोमो अचार मसाला | अवरु", desc: "अवरु मोमो अचार मसाला वीरेन्द्रनगरमा परीक्षण हुँदै गरेको गोलभेँडा र टिमुरको मोमो डुबाउने अचार बनाउन प्रयोग हुने सुक्खा मिश्रण हो।", h1: "मोमो अचार मसाला, सरल रूपमा।", eyebrow: "परीक्षणमा रहेको पहिलो उत्पादन", body: `<section class="page-hero wrap narrow"><p class="eyebrow">परीक्षणमा रहेको पहिलो उत्पादन</p><h1>मोमो अचार मसाला, सरल रूपमा।</h1><p class="lede">यो मोमोसँग दिइने गोलभेँडा र टिमुरको डुबाउने अचार बनाउन प्रयोग हुने सुक्खा मसलाको मिश्रण हो।</p><div class="actions"><a class="button" href="${wa.tester}" target="_blank" rel="noopener">परीक्षणमा सहभागी हुन सोध्नुहोस्</a><a class="text-link" href="#questions">सामान्य प्रश्न पढ्नुहोस्</a></div></section><section class="process wrap"><div class="section-head"><p class="eyebrow">भिन्नता</p><h2>सुक्खा मसला → तयारी → डुबाउने अचार</h2></div><ol class="steps"><li><span>०१</span><strong>मोमो अचार मसाला</strong><p>सुक्खा मसलाको मिश्रण। अवरुको परीक्षण भइरहेको उत्पादन यही हो।</p></li><li><span>०२</span><strong>तयारी</strong><p>गोलभेँडा र टिमुरको अचार बनाउँदा मिश्रण प्रयोग गरिन्छ। अन्तिम विधि स्वीकृत भएको छैन।</p></li><li><span>०३</span><strong>मोमो अचार</strong><p>मोमोसँग दिइने तयार डुबाउने सस। प्याकभित्र बिक्री हुने वस्तु यो होइन।</p></li></ol></section><section class="facts wrap"><div><p class="eyebrow">आजसम्म पक्का</p><h2>अनुमानबिनाका स्पष्ट तथ्य</h2></div><dl><div><dt>उत्पादनको प्रकार</dt><dd>सुक्खा मसलाको मिश्रण</dd></div><div><dt>प्रयोग</dt><dd>गोलभेँडा र टिमुरको मोमो डुबाउने अचार बनाउने</dd></div><div><dt>परीक्षण स्थान</dt><dd>वीरेन्द्रनगर, सुर्खेत, नेपाल</dd></div><div><dt>अझै अन्तिम हुँदै</dt><dd>रेसिपी, विधि, प्याकको आकार, मूल्य, उपलब्धता र सार्वजनिक हुने मिति</dd></div></dl></section><section class="faq wrap narrow" id="questions"><p class="eyebrow">सामान्य प्रश्न</p><h2>सिधा उत्तर</h2><details open><summary>मोमो अचार मसाला के हो?</summary><p>यो मोमोसँग दिइने गोलभेँडा र टिमुरको डुबाउने अचार बनाउँदा प्रयोग हुने सुक्खा मसलाको मिश्रण हो।</p></details><details><summary>के यो खान तयार अचार हो?</summary><p>होइन। मसाला अचार बनाउन प्रयोग गरिने सामग्री हो; यो खान तयार सस होइन।</p></details><details><summary>के यो मोमोको भराइमा हालिन्छ?</summary><p>होइन। यो मोमोको भित्रको भराइका लागि होइन, डुबाउने अचारका लागि हो।</p></details><details><summary>के अहिले किन्न पाइन्छ?</summary><p>व्यापारिक विवरण स्वीकृत भएका छैनन्। उत्पादन अहिले वीरेन्द्रनगरमा परीक्षण हुँदैछ।</p></details><details><summary>परीक्षणमा कसरी सहभागी हुने?</summary><p>अवरुलाई WhatsApp सन्देश पठाउनुहोस्। अहिलेको परीक्षण चरण तपाईंका लागि उपयुक्त भए/नभएको जानकारी दिनेछौँ।</p></details></section>` },
    { slug: "testing", key: "testing", title: "उत्पादन परीक्षणमा सहभागी हुनुहोस् | अवरु", desc: "वीरेन्द्रनगरमा अवरु मोमो अचार मसाला परीक्षण गर्न चाहनुहुन्छ? WhatsApp मा आफ्नो रुचि पठाउनुहोस्।", h1: "पकाउनुहोस्। चाख्नुहोस्। के काम गर्‍यो भन्नुहोस्।", eyebrow: "परीक्षणमा सहभागी हुनुहोस्", body: `<section class="page-hero wrap narrow"><p class="eyebrow">परीक्षणमा सहभागी हुनुहोस्</p><h1>पकाउनुहोस्। चाख्नुहोस्। के काम गर्‍यो भन्नुहोस्।</h1><p class="lede">व्यापारिक विवरण अन्तिम हुनुअघि अवरु मोमो अचार मसाला परीक्षण गर्न वीरेन्द्रनगर र वरपरका इच्छुक घरका भान्सेलाई आमन्त्रण गर्दैछौँ।</p></section><section class="testing-grid wrap"><div><h2>परीक्षण भनेको के हो</h2><ol class="number-list"><li><span>१</span><p><strong>आफ्नो रुचि बताउनुहोस्।</strong><br>तलको बटनबाट छोटो WhatsApp कुराकानी सुरु गर्नुहोस्।</p></li><li><span>२</span><p><strong>हामी उपयुक्तता पुष्टि गर्छौँ।</strong><br>अवसर स्थान र परीक्षणको हालको चरणमा निर्भर हुन सक्छ।</p></li><li><span>३</span><p><strong>बनाएर प्रतिक्रिया दिनुहोस्।</strong><br>स्पष्टता, तयारी र तपाईंले पस्कन चाहने नतिजाबारे इमानदार टिप्पणी चाहन्छौँ।</p></li></ol></div><aside class="contact-card"><p class="eyebrow">WhatsApp बाट सुरु गर्नुहोस्</p><h2>परीक्षण गर्न इच्छुक हुनुहुन्छ?</h2><p>लिङ्कले पहिल्यै लेखिएको सन्देश खोल्छ। WhatsApp ले तपाईंको फोन नम्बर र तपाईंले पठाउन रोजेको जानकारी सिधै अवरुसँग बाँड्छ।</p><a class="button button-dark" href="${wa.tester}" target="_blank" rel="noopener">अवरुलाई सन्देश पठाउनुहोस्</a><p class="micro">वेबसाइट फारम वा लुकेको तथ्याङ्क सङ्कलन छैन।</p></aside></section>` },
    { slug: "contact", key: "contact", title: "अवरुलाई सम्पर्क गर्नुहोस् | परीक्षण र खुद्रा विक्रेता सोधपुछ", desc: "उत्पादन परीक्षण, खुद्रा विक्रेता कुराकानी वा सामान्य प्रश्नका लागि अवरुलाई WhatsApp मा सम्पर्क गर्नुहोस्।", h1: "एउटा नम्बर, तीन स्पष्ट कुराकानी।", eyebrow: "अवरुलाई सम्पर्क", body: `<section class="page-hero wrap narrow"><p class="eyebrow">अवरुलाई सम्पर्क</p><h1>एउटा नम्बर, तीन स्पष्ट कुराकानी।</h1><p class="lede">सन्देशको कारण छान्नुहोस् र WhatsApp सही परिचयसहित खुल्छ। हामी अहिले वीरेन्द्रनगर, सुर्खेत, नेपालमा परीक्षण गर्दैछौँ।</p></section><section class="contact-options wrap"><article><span>०१</span><h2>घरका भान्से</h2><p>मोमो अचार मसाला परीक्षणमा सहभागी हुनेबारे सोध्नुहोस्।</p><a class="text-link" href="${wa.tester}" target="_blank" rel="noopener">उत्पादन परीक्षणमा सहभागी हुनुहोस्</a></article><article><span>०२</span><h2>खुद्रा विक्रेता</h2><p>भविष्यमा अवरु राख्ने सम्भावनाबारे कुराकानी सुरु गर्नुहोस्। उपलब्धता पक्का छैन।</p><a class="text-link" href="${wa.retailer}" target="_blank" rel="noopener">खुद्रा विक्रेता सोधपुछ</a></article><article><span>०३</span><h2>सामान्य प्रश्न</h2><p>अवरु वा परीक्षणमा रहेको उत्पादनबारे अरू कुरा सोध्नुहोस्।</p><a class="text-link" href="${wa.general}" target="_blank" rel="noopener">सामान्य सोधपुछ पठाउनुहोस्</a></article></section><section class="banner"><div class="wrap"><p class="eyebrow">WhatsApp</p><h2>+977 9822403262</h2><p>हामीले कार्यालयको ठेगाना, इमेल वा खुल्ने समय सार्वजनिक गरेका छैनौँ।</p></div></section>` }
  ]
};

function pairedPath(locale, slug) { return `${copy[locale].switchPrefix}${slug ? `/${slug}` : ""}/`.replace("//", "/"); }
function pagePath(locale, slug) { return `${copy[locale].prefix}${slug ? `/${slug}` : ""}/`.replace("//", "/"); }
function nav(locale, key) { const c = copy[locale]; return c.nav.map(([label, href]) => `<a href="${href}"${(key === "home" && href === (locale === "en" ? "/" : "/ne/")) || href.includes(`/${key}/`) ? ' aria-current="page"' : ""}>${label}</a>`).join(""); }
function schema(page, locale) {
  const organization = {"@context":"https://schema.org","@type":"Organization","name":"Avaru","description": locale === "en" ? "A masala and spices brand being developed for Nepali kitchens." : "नेपाली भान्साका लागि विकास हुँदै गरेको मसला ब्रान्ड।","areaServed":{"@type":"Place","name":"Birendranagar, Surkhet, Nepal"},"contactPoint":{"@type":"ContactPoint","telephone":"+9779822403262","contactType":"customer service","availableLanguage":["English","Nepali"]}};
  if (page.key === "product") return [organization,{"@context":"https://schema.org","@type":"Product","name":locale === "en" ? "Avaru Momo Achar Masala" : "अवरु मोमो अचार मसाला","brand":{"@type":"Brand","name":"Avaru"},"category":"Dry spice blend","description":page.desc}];
  return organization;
}
function render(page, locale) {
  const c = copy[locale], canonical = `${origin}${pagePath(locale, page.slug)}`;
  const alternate = `${origin}${pairedPath(locale, page.slug)}`;
  return `<!doctype html><html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.desc}"><meta name="robots" content="noindex,nofollow"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="${locale}" href="${canonical}"><link rel="alternate" hreflang="${locale === "en" ? "ne" : "en"}" href="${alternate}"><link rel="alternate" hreflang="x-default" href="${origin}/${page.slug ? `${page.slug}/` : ""}"><meta property="og:type" content="website"><meta property="og:site_name" content="Avaru"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.desc}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}/assets/og-avaru.png"><meta property="og:image:alt" content="Avaru — Masalas for Nepali kitchens, shown with momo and dipping achar"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${page.title}"><meta name="twitter:description" content="${page.desc}"><meta name="twitter:image" content="${origin}/assets/og-avaru.png"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${JSON.stringify(schema(page, locale)).replaceAll("<", "\\u003c")}</script></head><body><a class="skip" href="#main">${c.skip}</a><div class="preview-bar">${c.private}</div><header class="site-header"><a class="brand" href="${c.prefix || "/"}" aria-label="Avaru home">Avaru<span>अवरु</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span>${c.menu}</span><i aria-hidden="true"></i></button><nav id="site-nav" aria-label="Primary navigation">${nav(locale, page.key)}</nav><a class="lang" href="${pairedPath(locale, page.slug)}" hreflang="${locale === "en" ? "ne" : "en"}">${c.switchLabel}</a></header><main id="main">${page.body}</main><footer><div class="wrap footer-grid"><div><a class="brand brand-light" href="${c.prefix || "/"}">Avaru<span>अवरु</span></a><p>${c.footer}</p></div><div><p class="footer-label">${locale === "en" ? "Currently" : "अहिले"}</p><p>${c.location}</p></div><div><p class="footer-label">${locale === "en" ? "Talk to us" : "सम्पर्क"}</p><a href="${wa.general}" target="_blank" rel="noopener">WhatsApp +977 9822403262</a></div></div><div class="wrap footer-bottom"><span>© 2026 Avaru</span><span>${locale === "en" ? "No social accounts published yet." : "सामाजिक सञ्जाल खाता अझै सार्वजनिक छैन।"}</span></div></footer><script src="/assets/site.js" defer></script></body></html>`;
}

await rm(dist, {recursive:true, force:true});
await mkdir(path.join(dist, "assets"), {recursive:true});
for (const locale of ["en","ne"]) for (const page of pages[locale]) {
  const dir = path.join(dist, pagePath(locale, page.slug));
  await mkdir(dir, {recursive:true});
  await writeFile(path.join(dir, "index.html"), render(page, locale));
}
await cp(path.join(root,"src","assets"), path.join(dist,"assets"), {recursive:true});
await cp(path.join(root,"src","site.css"), path.join(dist,"assets","site.css"));
await cp(path.join(root,"src","site.js"), path.join(dist,"assets","site.js"));
await cp(path.join(root,"src","favicon.svg"), path.join(dist,"favicon.svg"));
const urls = pages.en.flatMap(p => [`${origin}${pagePath("en",p.slug)}`,`${origin}${pagePath("ne",p.slug)}`]);
await writeFile(path.join(dist,"sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join("")}</urlset>`);
await writeFile(path.join(dist,"robots.txt"), "User-agent: *\nDisallow: /\n# Private preview. Enable indexing only after a public domain is approved.\n");
console.log(`Built ${urls.length} localized pages in ${dist}`);
