import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const dist = path.join(root, "dist");
const productionHost = process.env.VERCEL_PROJECT_PRODUCTION_URL;
const origin = productionHost
  ? `https://${productionHost}`
  : "https://avaru-spices-surkhet.surkhettimes05.chatgpt.site";

const wa = {
  tester: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%27m%20interested%20in%20joining%20the%20Momo%20Achar%20Masala%20product%20testing%20in%20Birendranagar.",
  consumer: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%20want%20to%20know%20where%20I%20can%20get%20Avaru%20Momo%20Achar%20Masala%20or%20join%20the%20current%20testing%20in%20Birendranagar.%20Please%20share%20current%20availability.",
  feedback: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%20want%20to%20test%20Momo%20Achar%20Masala%20and%20share%20feedback.%20My%20location%3A%20__%20I%20usually%20make%20momo%20achar%3A%20__%20What%20I%20care%20about%20most%20(taste%2Ftimur%2Fheat%2Fease)%3A%20__",
  retailer: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%20run%20a%20retail%20or%20distribution%20business%20and%20want%20to%20stock%20Avaru%20Momo%20Achar%20Masala.%20Shop%2Fbusiness%20name%3A%20__%20Location%3A%20__%20Expected%20quantity%3A%20__",
  general: "https://wa.me/9779822403262?text=Namaste%20Avaru%2C%20I%20have%20a%20general%20enquiry."
};

const copy = {
  en: {
    lang: "en", prefix: "", switchLabel: "नेपाली", switchPrefix: "/ne",
    nav: [["Home", "/"], ["About", "/about/"], ["Our masalas", "/products/"], ["Product testing", "/testing/"], ["Contact", "/contact/"]],
    footer: "Masalas and spice blends for Nepali kitchens.", location: "Testing in Birendranagar, Surkhet, Nepal",
    private: "अहिले वीरेन्द्रनगरमा परीक्षण हुँदैछ • Momo Achar Masala is in active product testing in Birendranagar.",
    menu: "Menu", close: "Close menu", skip: "Skip to content"
  },
  ne: {
    lang: "ne", prefix: "/ne", switchLabel: "English", switchPrefix: "",
    nav: [["गृहपृष्ठ", "/ne/"], ["हाम्रो बारेमा", "/ne/about/"], ["हाम्रा मसला", "/ne/products/"], ["उत्पादन परीक्षण", "/ne/testing/"], ["सम्पर्क", "/ne/contact/"]],
    footer: "नेपाली भान्साका लागि मसला र मसलाका मिश्रण।", location: "वीरेन्द्रनगर, सुर्खेत, नेपालमा परीक्षण हुँदैछ",
    private: "अहिले वीरेन्द्रनगरमा उत्पादन परीक्षण हुँदैछ • Momo Achar Masala is being tested in Birendranagar.",
    menu: "मेनु", close: "मेनु बन्द गर्नुहोस्", skip: "मुख्य सामग्रीमा जानुहोस्"
  }
};

const pages = {
  en: [
    { slug: "", key: "home", title: "Avaru | Masalas made for the food Nepal actually eats", desc: "Avaru is a Nepali masala brand building purpose-built spice blends for familiar Nepali food. Momo Achar Masala is the first blend in testing, with Dal, Masu, Tarkari, Sekuwa and more planned.", h1: "Masalas made for the food Nepal actually eats.", eyebrow: "AVARU / अवरु", body: `
      <section class="brand-hero wrap">
        <div class="brand-hero-copy">
          <p class="eyebrow">AVARU / अवरु</p>
          <h1><span class="ne-line">नेपालले साँच्चै खाने परिकारका लागि मसला।</span><span class="en-line">Masalas made for the food Nepal actually eats.</span></h1>
          <p class="brand-promise">Purpose-built spice blends that make familiar Nepali food easier to get right.</p>
          <p class="brand-food-line">Dal. Tarkari. Masu. Momo. Achar. Sekuwa.</p>
          <p class="lede">अवरु केवल एउटा “मसला” बेच्ने ब्रान्ड होइन। हामी परिचित नेपाली परिकारका लागि <strong>specific cooking outcomes</strong> बनाउने focused blends विकास गर्दैछौँ।</p>
          <div class="actions buy-actions"><a class="button" href="#range">हाम्रा मसला • Explore the range</a><a class="button button-outline" href="${wa.retailer}" target="_blank" rel="noopener">पसलमा राख्नुस् • Stock Avaru</a></div>
        </div>
        <aside class="first-blend-card">
          <span class="status status-live">SKU #1 • Testing now in Birendranagar</span>
          <p class="eyebrow">हाम्रो पहिलो blend • Our first blend</p>
          <h2>मोमो अचार मसाला<br><small>Momo Achar Masala</small></h2>
          <div class="not-ready-callout"><strong>Dry masala to help you make momo achar — not ready achar.</strong><span>यो मोमो अचार बनाउन प्रयोग हुने सुक्खा मसला हो — तयार अचार होइन।</span></div>
          <dl class="launch-facts">
            <div><dt>Product</dt><dd>Dry spice blend</dd></div>
            <div><dt>For</dt><dd>Tomato-and-timur momo dipping achar</dd></div>
            <div><dt>Stage</dt><dd>Active product testing</dd></div>
            <div><dt>Pack / MRP</dt><dd>Not approved yet</dd></div>
            <div><dt>Availability</dt><dd>Ask about current Birendranagar testing</dd></div>
          </dl>
          <a class="button button-dark" href="${wa.consumer}" target="_blank" rel="noopener">कहाँ पाइन्छ? • Where to buy</a>
        </aside>
      </section>

      <section class="brand-thesis">
        <div class="wrap brand-thesis-grid">
          <div><p class="eyebrow">Avaru को काम • What Avaru does</p><h2>We start with the dish, not the spice shelf.</h2></div>
          <div class="outcome-example"><span>“Great momo achar”</span><b>→</b><strong>Avaru Momo Achar Masala</strong></div>
          <div class="outcome-example"><span>“Better everyday dal”</span><b>→</b><strong>Avaru Dal Masala</strong></div>
          <div class="outcome-example"><span>“Nepali-style masu that tastes right”</span><b>→</b><strong>Avaru Masu Masala</strong></div>
        </div>
      </section>

      <section class="range-section wrap" id="range">
        <div class="section-head range-head"><div><p class="eyebrow">Avaru range architecture</p><h2>One focused first product. A much bigger masala house behind it.</h2></div><p class="section-note">Only Momo Achar Masala is in active testing. Everything else below is a planned direction—not a launched-product claim.</p></div>
        <div class="range-groups">
          <article class="range-group"><div class="range-group-head"><span>01</span><div><h3>Nepali Favourites</h3><p>Distinctive blends around foods people already recognise and crave.</p></div></div><div class="range-products"><div class="range-product live"><b>Momo Achar Masala</b><small>Testing now • SKU #1</small></div><div class="range-product"><b>Sekuwa Masala</b><small>Planned • distinctive next-wave blend</small></div><div class="range-product"><b>Choila Masala</b><small>Planned • later</small></div></div></article>
          <article class="range-group"><div class="range-group-head"><span>02</span><div><h3>Everyday Cooking</h3><p>High-frequency blends designed for the foods cooked again and again.</p></div></div><div class="range-products"><div class="range-product priority"><b>Dal Masala</b><small>Priority #2 candidate</small></div><div class="range-product"><b>Masu / Meat Masala</b><small>Priority #3</small></div><div class="range-product"><b>Tarkari Masala</b><small>Priority #4</small></div></div></article>
          <article class="range-group"><div class="range-group-head"><span>03</span><div><h3>Achar & Quick Solutions</h3><p>Future signature blends and convenience products with a clear cooking job.</p></div></div><div class="range-products"><div class="range-product"><b>Achar blends</b><small>Planned signature direction</small></div><div class="range-product"><b>Chicken Curry / Curry Base</b><small>Planned convenience direction</small></div></div></article>
        </div>
      </section>

      <section class="why-avaru">
        <div class="wrap"><div class="section-head"><div><p class="eyebrow">किन Avaru? • Why Avaru</p><h2>Focused blends for familiar food. Less guessing in the kitchen.</h2></div></div>
          <div class="why-grid"><article><span>01</span><strong>Food-first</strong><p>We design around a real cooking outcome—momo achar, dal, masu, sekuwa—not around another generic spice shelf.</p></article><article><span>02</span><strong>Nepali kitchen-first</strong><p>The reference point is food people here already cook, serve and understand.</p></article><article><span>03</span><strong>Specific before broad</strong><p>Each blend needs a clear job. We would rather solve one dish well than launch ten vague masalas.</p></article><article><span>04</span><strong>Test before scale</strong><p>Recipe, instructions, pack and price are validated before we call a product ready.</p></article></div>
        </div>
      </section>

      <section class="use-flow-section">
        <div class="wrap">
          <div class="section-head compact-head"><div><p class="eyebrow">SKU #1 कसरी काम गर्छ? • How the first blend works</p><h2>Dry masala → Make achar → Serve with momo.</h2></div></div>
          <ol class="use-flow" aria-label="How Avaru Momo Achar Masala is used">
            <li><span class="flow-number">01</span><div class="flow-icon" aria-hidden="true">✦</div><strong>सुक्खा मसला<br><small>Dry masala</small></strong><p>Open the Avaru dry spice blend used for momo dipping achar.</p></li>
            <li><span class="flow-number">02</span><div class="flow-arrow" aria-hidden="true">→</div><div class="flow-icon" aria-hidden="true">◉</div><strong>अचार बनाउनुहोस्<br><small>Make achar</small></strong><p>Use the current test dosage while preparing your tomato-and-timur achar base.</p></li>
            <li><span class="flow-number">03</span><div class="flow-arrow" aria-hidden="true">→</div><div class="flow-icon" aria-hidden="true">🥟</div><strong>मोमोसँग पस्कनुहोस्<br><small>Serve with momo</small></strong><p>Blend to your preferred consistency, taste, then serve beside hot momo.</p></li>
          </ol>
        </div>
      </section>

      <section class="recipe-testing wrap">
        <article class="recipe-card">
          <p class="eyebrow">परीक्षण प्रयोग विधि • Trial usage guide</p><h2>How to use the current test sample</h2>
          <p class="recipe-note"><strong>Not the final retail recipe.</strong> Exact masala quantity is still being tested. Testers should use the dosage supplied with their current sample.</p>
          <ol class="recipe-steps"><li><span>1</span><div><strong>Prepare the achar base.</strong><p>Cook or roast tomato and your usual supporting ingredients such as garlic/chilli according to your household method.</p></div></li><li><span>2</span><div><strong>Add the current Avaru test dosage.</strong><p>Add the amount supplied with the trial sample, then blend or grind it into the tomato base.</p></div></li><li><span>3</span><div><strong>Finish to your taste.</strong><p>Adjust salt, acidity and water/consistency as needed. Serve beside momo and note what you would change.</p></div></li></ol>
        </article>
        <aside class="testing-focus"><span class="status status-live">Active testing • वीरेन्द्रनगर</span><p class="eyebrow">हामी के परीक्षण गर्दैछौँ? • What we are testing</p><h2>Your feedback decides the final first product.</h2><ul class="testing-points"><li><strong>Taste balance</strong><span>Is the finished achar balanced and satisfying?</span></li><li><strong>Timur aroma</strong><span>Too weak, right, or overpowering?</span></li><li><strong>Heat level</strong><span>Does the spice level fit everyday households?</span></li><li><strong>Ease + consistency</strong><span>Are the instructions easy, and can you get a similar result again?</span></li></ul><a class="button button-dark feedback-button" href="${wa.feedback}" target="_blank" rel="noopener">Test it + send feedback on WhatsApp</a></aside>
      </section>

      <section class="buy-paths wrap">
        <article class="path-card consumer-path"><p class="eyebrow">घरका ग्राहक • Consumers</p><h2>पहिलो blend try गर्न चाहनुहुन्छ?</h2><p>Momo Achar Masala is currently being tested in Birendranagar. General retail availability is not yet announced.</p><a class="button button-dark" href="${wa.consumer}" target="_blank" rel="noopener">WhatsApp मा availability सोध्नुहोस्</a></article>
        <article class="path-card retailer-path"><p class="eyebrow">खुद्रा / वितरक • Retailer / Distributor</p><h2>अवरु range राख्न चाहनुहुन्छ?</h2><p>Start the conversation now. Send your shop/business name, location and expected quantity for the first release.</p><a class="button" href="${wa.retailer}" target="_blank" rel="noopener">Retailer / Distributor enquiry</a></article>
      </section>
      <nav class="mobile-buybar" aria-label="Quick buying actions"><a href="${wa.consumer}" target="_blank" rel="noopener">पहिलो blend</a><a href="${wa.retailer}" target="_blank" rel="noopener">Stock Avaru</a></nav>` },
    { slug: "about", key: "about", title: "About Avaru | A Nepali Masala House", desc: "Avaru builds purpose-built spice blends for familiar Nepali food, starting with Momo Achar Masala and expanding into everyday and distinctive Nepali cooking occasions.", h1: "A masala house built around the food Nepal actually eats.", eyebrow: "About Avaru", body: `<section class="page-hero wrap narrow"><p class="eyebrow">About Avaru / अवरु</p><h1>A masala house built around the food Nepal actually eats.</h1><p class="lede">Avaru is building purpose-built spice blends that make familiar Nepali food easier to get right. We start with a cooking outcome—not with a commodity spice catalogue.</p></section><section class="split wrap"><div><h2>Specific products. Broad ambition.</h2><p>Our first product is deliberately narrow: Momo Achar Masala. The brand is not. Avaru is being built to cover Nepali favourites, everyday cooking, achar-focused blends and useful kitchen solutions.</p></div><div><h2>Test first. Scale second.</h2><p>We would rather validate recipe, instructions, price and repeat use on one product than create a shelf full of weak launches. Momo Achar Masala is the proving ground for the wider Avaru system.</p></div></section><section class="brand-principles wrap"><article><span>01</span><h3>Food-first</h3><p>Start from dal, masu, momo, achar, sekuwa—not from “we need another spice SKU.”</p></article><article><span>02</span><h3>Outcome-led</h3><p>Every blend needs a clear job in the kitchen.</p></article><article><span>03</span><h3>Nepali-first</h3><p>Language, food references and use cases should feel native to the customer.</p></article><article><span>04</span><h3>Earn the range</h3><p>Future products stay planned until testing justifies release.</p></article></section>` },
    { slug: "products", key: "products", title: "Avaru Masala Range | Planned Nepali Spice Blends", desc: "Explore Avaru's masala architecture: Momo Achar Masala in testing, plus planned Dal, Masu, Tarkari, Sekuwa, Choila, achar and curry blends.", h1: "A focused range for the foods Nepal actually cooks.", eyebrow: "Our masalas", body: `<section class="page-hero wrap narrow"><p class="eyebrow">Our masalas / हाम्रा मसला</p><h1>A focused range for the foods Nepal actually cooks.</h1><p class="lede">One product is in active testing today. The wider range below shows where Avaru is going without pretending planned products are already on sale.</p></section><section class="range-section wrap"><div class="range-groups"><article class="range-group"><div class="range-group-head"><span>01</span><div><h3>Nepali Favourites</h3></div></div><div class="range-products"><a class="range-product live" href="/products/momo-achar-masala/"><b>Momo Achar Masala</b><small>Testing now • SKU #1</small></a><div class="range-product"><b>Sekuwa Masala</b><small>Planned</small></div><div class="range-product"><b>Choila Masala</b><small>Planned</small></div></div></article><article class="range-group"><div class="range-group-head"><span>02</span><div><h3>Everyday Cooking</h3></div></div><div class="range-products"><div class="range-product priority"><b>Dal Masala</b><small>Priority #2 candidate</small></div><div class="range-product"><b>Masu / Meat Masala</b><small>Priority #3</small></div><div class="range-product"><b>Tarkari Masala</b><small>Priority #4</small></div></div></article><article class="range-group"><div class="range-group-head"><span>03</span><div><h3>Achar & Quick Solutions</h3></div></div><div class="range-products"><div class="range-product"><b>Achar blends</b><small>Planned signature direction</small></div><div class="range-product"><b>Chicken Curry / Curry Base</b><small>Planned convenience direction</small></div></div></article></div></section>` },
    { slug: "products/momo-achar-masala", key: "product", title: "Momo Achar Masala | Avaru", desc: "Avaru Momo Achar Masala is a dry spice blend being tested for preparing tomato-and-timur momo dipping achar in Birendranagar, Nepal.", h1: "Momo Achar Masala, explained simply.", eyebrow: "First product in testing", body: `<section class="page-hero wrap narrow"><p class="eyebrow">First product in testing</p><h1>Momo Achar Masala, explained simply.</h1><p class="lede">It is a dry spice blend used as part of making tomato-and-timur momo dipping achar—the sauce served beside momo.</p><div class="actions"><a class="button" href="${wa.tester}" target="_blank" rel="noopener">Ask to join testing</a><a class="text-link" href="#questions">Read common questions</a></div></section><section class="process wrap"><div class="section-head"><p class="eyebrow">The distinction</p><h2>Dry masala → preparation → dipping achar</h2></div><ol class="steps"><li><span>01</span><strong>Momo achar masala</strong><p>A dry spice blend. This is the Avaru product being tested.</p></li><li><span>02</span><strong>Preparation</strong><p>Use the blend as part of preparing a tomato-and-timur achar. The final method is not yet approved.</p></li><li><span>03</span><strong>Momo achar</strong><p>The finished dipping sauce served with momo. This is not what is sold in the pouch.</p></li></ol></section><section class="facts wrap"><div><p class="eyebrow">Confirmed today</p><h2>Clear facts, without guesses</h2></div><dl><div><dt>Product type</dt><dd>Dry spice blend</dd></div><div><dt>Intended use</dt><dd>Preparing tomato-and-timur momo dipping achar</dd></div><div><dt>Testing location</dt><dd>Birendranagar, Surkhet, Nepal</dd></div><div><dt>Still being finalised</dt><dd>Recipe, method, pack size, price, availability and launch date</dd></div></dl></section><section class="faq wrap narrow" id="questions"><p class="eyebrow">Common questions</p><h2>Answers without the extra spice</h2><details open><summary>What is momo achar masala?</summary><p>It is a dry spice blend used while making the tomato-and-timur dipping achar served with momo.</p></details><details><summary>Is it a ready-made achar?</summary><p>No. The masala is an ingredient for preparing the achar; it is not a ready-to-eat sauce.</p></details><details><summary>Is it used in momo filling?</summary><p>No. It is intended for momo dipping achar, not the filling inside momo.</p></details><details><summary>Can I buy it now?</summary><p>Commercial details are not approved yet. The product is currently being tested in Birendranagar.</p></details><details><summary>How can I join testing?</summary><p>Send Avaru a WhatsApp message. We will let you know whether the current testing round is relevant to you.</p></details></section>` },
    { slug: "testing", key: "testing", title: "Join Product Testing | Avaru", desc: "Interested in testing Avaru Momo Achar Masala in Birendranagar? Contact Avaru on WhatsApp to share your interest.", h1: "Cook. Taste. Tell us what worked.", eyebrow: "Join the trial", body: `<section class="page-hero wrap narrow"><p class="eyebrow">Join the trial</p><h1>Cook. Taste. Tell us what worked.</h1><p class="lede">We are inviting relevant home cooks in and around Birendranagar to help us test Avaru Momo Achar Masala before commercial details are final.</p></section><section class="testing-grid wrap"><div><h2>What testing means</h2><ol class="number-list"><li><span>1</span><p><strong>Tell us you are interested.</strong><br>Start a short WhatsApp conversation using the button below.</p></li><li><span>2</span><p><strong>We confirm the fit.</strong><br>Testing opportunities may depend on location and the current stage of the trial.</p></li><li><span>3</span><p><strong>You prepare and share feedback.</strong><br>We want honest notes about clarity, preparation and the result you would serve.</p></li></ol></div><aside class="contact-card"><p class="eyebrow">Start on WhatsApp</p><h2>Interested in testing?</h2><p>The link opens a prefilled message. WhatsApp will share your phone number and any information you choose to send directly with Avaru.</p><a class="button button-dark" href="${wa.tester}" target="_blank" rel="noopener">Message Avaru</a><p class="micro">No website form or hidden data collection.</p></aside></section>` },
    { slug: "contact", key: "contact", title: "Contact Avaru | Testing and Retailer Enquiries", desc: "Contact Avaru on WhatsApp for product testing, retailer conversations or general questions in Birendranagar, Surkhet.", h1: "One number, three clear conversations.", eyebrow: "Contact Avaru", body: `<section class="page-hero wrap narrow"><p class="eyebrow">Contact Avaru</p><h1>One number, three clear conversations.</h1><p class="lede">Choose the reason for your message and WhatsApp will open with the right introduction. We are currently testing in Birendranagar, Surkhet, Nepal.</p></section><section class="contact-options wrap"><article><span>01</span><h2>Home cooks</h2><p>Ask about taking part in Momo Achar Masala testing.</p><a class="text-link" href="${wa.tester}" target="_blank" rel="noopener">Join product testing</a></article><article><span>02</span><h2>Retailers</h2><p>Start a conversation about future stocking possibilities. Availability is not yet confirmed.</p><a class="text-link" href="${wa.retailer}" target="_blank" rel="noopener">Make a retailer enquiry</a></article><article><span>03</span><h2>General questions</h2><p>Ask something else about Avaru or the product in testing.</p><a class="text-link" href="${wa.general}" target="_blank" rel="noopener">Send a general enquiry</a></article></section><section class="banner"><div class="wrap"><p class="eyebrow">WhatsApp</p><h2>+977 9822403262</h2><p>We have not published an office address, email address or opening hours.</p></div></section>` }
  ],
  ne: [
    { slug: "", key: "home", title: "अवरु | नेपालले साँच्चै खाने परिकारका लागि मसला", desc: "अवरु परिचित नेपाली खानाका लागि purpose-built spice blends बनाउने नेपाली मसला ब्रान्ड हो। पहिलो blend Momo Achar Masala परीक्षणमा छ; Dal, Masu, Tarkari, Sekuwa र अरू range योजना गरिएको छ।", h1: "नेपालले साँच्चै खाने परिकारका लागि मसला।", eyebrow: "AVARU / अवरु", body: `
      <section class="brand-hero wrap">
        <div class="brand-hero-copy">
          <p class="eyebrow">AVARU / अवरु</p>
          <h1><span class="ne-line">नेपालले साँच्चै खाने परिकारका लागि मसला।</span><span class="en-line">Masalas made for the food Nepal actually eats.</span></h1>
          <p class="brand-promise">परिचित नेपाली खाना सजिलै सही स्वादमा बनाउन मद्दत गर्ने purpose-built spice blends.</p>
          <p class="brand-food-line">दाल। तरकारी। मासु। मोमो। अचार। सेकुवा।</p>
          <p class="lede">अवरु केवल एउटा मसला बेच्ने ब्रान्ड होइन। हामी नेपाली भान्सामा पहिल्यै पकाइने परिचित परिकारका लागि <strong>स्पष्ट काम गर्ने focused blends</strong> विकास गर्दैछौँ।</p>
          <div class="actions buy-actions"><a class="button" href="#range">हाम्रा मसला हेर्नुहोस्</a><a class="button button-outline" href="${wa.retailer}" target="_blank" rel="noopener">पसलमा राख्नुस् • Stock Avaru</a></div>
        </div>
        <aside class="first-blend-card">
          <span class="status status-live">SKU #1 • वीरेन्द्रनगरमा परीक्षण</span><p class="eyebrow">हाम्रो पहिलो blend • Our first blend</p><h2>मोमो अचार मसाला<br><small>Momo Achar Masala</small></h2>
          <div class="not-ready-callout"><strong>यो मोमो अचार बनाउन प्रयोग हुने सुक्खा मसला हो — तयार अचार होइन।</strong><span>Dry masala to help you make momo achar — not ready achar.</span></div>
          <dl class="launch-facts"><div><dt>उत्पादन</dt><dd>सुक्खा मसलाको मिश्रण</dd></div><div><dt>काम</dt><dd>गोलभेँडा–टिमुरको मोमो अचार बनाउन</dd></div><div><dt>अवस्था</dt><dd>सक्रिय product testing</dd></div><div><dt>Pack / MRP</dt><dd>अझै स्वीकृत छैन</dd></div><div><dt>उपलब्धता</dt><dd>हालको Birendranagar testing बारे WhatsApp मा सोध्नुहोस्</dd></div></dl>
          <a class="button button-dark" href="${wa.consumer}" target="_blank" rel="noopener">कहाँ पाइन्छ? • Where to buy</a>
        </aside>
      </section>

      <section class="brand-thesis"><div class="wrap brand-thesis-grid"><div><p class="eyebrow">Avaru को काम • What Avaru does</p><h2>हामी spice shelf बाट होइन, परिकारबाट सुरु गर्छौँ।</h2></div><div class="outcome-example"><span>“राम्रो मोमो अचार”</span><b>→</b><strong>Avaru Momo Achar Masala</strong></div><div class="outcome-example"><span>“दैनिक अझ राम्रो दाल”</span><b>→</b><strong>Avaru Dal Masala</strong></div><div class="outcome-example"><span>“सही स्वादको नेपाली मासु”</span><b>→</b><strong>Avaru Masu Masala</strong></div></div></section>

      <section class="range-section wrap" id="range">
        <div class="section-head range-head"><div><p class="eyebrow">Avaru range architecture</p><h2>पहिलो उत्पादन focused छ। त्यसपछाडि ठूलो नेपाली मसला house बनाउने योजना छ।</h2></div><p class="section-note">Momo Achar Masala मात्र अहिले active testing मा छ। तलका बाँकी नाम planned directions हुन्—launched products होइनन्।</p></div>
        <div class="range-groups">
          <article class="range-group"><div class="range-group-head"><span>०१</span><div><h3>Nepali Favourites</h3><p>पहिल्यै परिचित र चाहना हुने नेपाली खानाका लागि distinctive blends.</p></div></div><div class="range-products"><div class="range-product live"><b>Momo Achar Masala</b><small>अहिले परीक्षणमा • SKU #1</small></div><div class="range-product"><b>Sekuwa Masala</b><small>Planned • distinctive next-wave blend</small></div><div class="range-product"><b>Choila Masala</b><small>Planned • later</small></div></div></article>
          <article class="range-group"><div class="range-group-head"><span>०२</span><div><h3>Everyday Cooking</h3><p>बारम्बार पकाइने खानाका लागि high-frequency blends.</p></div></div><div class="range-products"><div class="range-product priority"><b>Dal Masala</b><small>Priority #2 candidate</small></div><div class="range-product"><b>Masu / Meat Masala</b><small>Priority #3</small></div><div class="range-product"><b>Tarkari Masala</b><small>Priority #4</small></div></div></article>
          <article class="range-group"><div class="range-group-head"><span>०३</span><div><h3>Achar & Quick Solutions</h3><p>स्पष्ट cooking job भएका future signature blends र convenience products.</p></div></div><div class="range-products"><div class="range-product"><b>Achar blends</b><small>Planned signature direction</small></div><div class="range-product"><b>Chicken Curry / Curry Base</b><small>Planned convenience direction</small></div></div></article>
        </div>
      </section>

      <section class="why-avaru"><div class="wrap"><div class="section-head"><div><p class="eyebrow">किन Avaru? • Why Avaru</p><h2>परिचित खानाका लागि focused blends. भान्सामा कम guessing.</h2></div></div><div class="why-grid"><article><span>०१</span><strong>Food-first</strong><p>Generic spice shelf होइन—मोमो अचार, दाल, मासु, सेकुवा जस्तो वास्तविक cooking outcome बाट सुरु।</p></article><article><span>०२</span><strong>Nepali kitchen-first</strong><p>Reference point भनेको यहाँका मानिसले पहिल्यै पकाउने, खाने र बुझ्ने खाना हो।</p></article><article><span>०३</span><strong>Specific before broad</strong><p>हरेक blend को स्पष्ट काम हुनुपर्छ। दस अस्पष्ट मसला भन्दा एउटा dish राम्रो solve गर्नु महत्त्वपूर्ण।</p></article><article><span>०४</span><strong>Test before scale</strong><p>Recipe, instructions, pack र price validate भएपछि मात्र ready भनिन्छ।</p></article></div></div></section>

      <section class="use-flow-section"><div class="wrap"><div class="section-head compact-head"><div><p class="eyebrow">SKU #1 कसरी काम गर्छ?</p><h2>सुक्खा मसला → अचार बनाउनुहोस् → मोमोसँग पस्कनुहोस्</h2></div></div><ol class="use-flow"><li><span class="flow-number">०१</span><div class="flow-icon">✦</div><strong>सुक्खा मसला<br><small>Dry masala</small></strong><p>मोमो अचारका लागि Avaru dry spice blend.</p></li><li><span class="flow-number">०२</span><div class="flow-arrow">→</div><div class="flow-icon">◉</div><strong>अचार बनाउनुहोस्<br><small>Make achar</small></strong><p>गोलभेँडा–टिमुरको base बनाउँदा हालको test dosage प्रयोग गर्नुहोस्।</p></li><li><span class="flow-number">०३</span><div class="flow-arrow">→</div><div class="flow-icon">🥟</div><strong>मोमोसँग पस्कनुहोस्<br><small>Serve with momo</small></strong><p>आफूलाई मन पर्ने consistency मा बनाएर तातो मोमोसँग पस्कनुहोस्।</p></li></ol></div></section>

      <section class="recipe-testing wrap"><article class="recipe-card"><p class="eyebrow">परीक्षण प्रयोग विधि • Trial usage guide</p><h2>हालको test sample कसरी प्रयोग गर्ने?</h2><p class="recipe-note"><strong>यो अन्तिम retail recipe होइन।</strong> कति मसला प्रयोग गर्ने भन्ने कुरा अझै परीक्षणमा छ। Sample सँग दिइएको dosage प्रयोग गर्नुहोस्।</p><ol class="recipe-steps"><li><span>१</span><div><strong>अचारको base तयार गर्नुहोस्।</strong><p>आफ्नो घरको तरिकाअनुसार गोलभेँडा र सहयोगी सामग्री तयार गर्नुहोस्।</p></div></li><li><span>२</span><div><strong>हालको Avaru test dosage थप्नुहोस्।</strong><p>Trial sample सँग दिइएको मात्रामा मसला हालेर base सँग पिस्नु वा blend गर्नुहोस्।</p></div></li><li><span>३</span><div><strong>आफ्नो स्वादअनुसार पूरा गर्नुहोस्।</strong><p>नुन, अमिलोपन र पानी/consistency मिलाएर मोमोसँग पस्कनुहोस्।</p></div></li></ol></article><aside class="testing-focus"><span class="status status-live">वीरेन्द्रनगरमा सक्रिय परीक्षण</span><p class="eyebrow">हामी के परीक्षण गर्दैछौँ?</p><h2>तपाईंको feedback ले पहिलो product तय गर्न मद्दत गर्छ।</h2><ul class="testing-points"><li><strong>स्वादको सन्तुलन</strong><span>तयार अचार सन्तुलित छ?</span></li><li><strong>टिमुरको बास्ना</strong><span>कम, ठीक वा धेरै?</span></li><li><strong>पिरोको स्तर</strong><span>दैनिक खान मिल्ने?</span></li><li><strong>सजिलोपन + consistency</strong><span>निर्देशन बुझ्न सजिलो र repeatable छ?</span></li></ul><a class="button button-dark feedback-button" href="${wa.feedback}" target="_blank" rel="noopener">Test गर्नुहोस् + feedback दिनुहोस्</a></aside></section>

      <section class="buy-paths wrap"><article class="path-card consumer-path"><p class="eyebrow">घरका ग्राहक • Consumers</p><h2>पहिलो blend try गर्न चाहनुहुन्छ?</h2><p>Momo Achar Masala अहिले Birendranagar मा testing मा छ। सामान्य retail availability अझै घोषणा भएको छैन।</p><a class="button button-dark" href="${wa.consumer}" target="_blank" rel="noopener">Availability सोध्नुहोस्</a></article><article class="path-card retailer-path"><p class="eyebrow">खुद्रा / वितरक</p><h2>Avaru range राख्न चाहनुहुन्छ?</h2><p>पहिलो release का लागि पसल/व्यवसायको नाम, location र expected quantity पठाएर अहिले नै conversation सुरु गर्नुहोस्।</p><a class="button" href="${wa.retailer}" target="_blank" rel="noopener">Retailer / Distributor enquiry</a></article></section>
      <nav class="mobile-buybar"><a href="${wa.consumer}" target="_blank" rel="noopener">पहिलो blend</a><a href="${wa.retailer}" target="_blank" rel="noopener">Stock Avaru</a></nav>` },
    { slug: "about", key: "about", title: "अवरुबारे | नेपाली मसला house", desc: "अवरु परिचित नेपाली खानाका लागि purpose-built spice blends बनाउने मसला brand हो। सुरुवात Momo Achar Masala बाट हुन्छ र भविष्यमा everyday तथा distinctive blends मा विस्तार हुन्छ।", h1: "नेपालले साँच्चै खाने खानाबाट बनेको मसला house.", eyebrow: "अवरुबारे", body: `<section class="page-hero wrap narrow"><p class="eyebrow">About Avaru / अवरु</p><h1>नेपालले साँच्चै खाने खानाबाट बनेको मसला house.</h1><p class="lede">अवरुले परिचित नेपाली खाना सजिलै सही स्वादमा बनाउन मद्दत गर्ने purpose-built spice blends बनाउँदैछ। हामी commodity spice catalogue बाट होइन, cooking outcome बाट सुरु गर्छौँ।</p></section><section class="split wrap"><div><h2>उत्पादन specific. Ambition ठूलो।</h2><p>पहिलो उत्पादन जानाजानी narrow छ: Momo Achar Masala. तर brand narrow होइन। Avaru लाई Nepali favourites, everyday cooking, achar blends र useful kitchen solutions सम्म विस्तार हुने गरी बनाइँदैछ।</p></div><div><h2>पहिला test. त्यसपछि scale.</h2><p>कमजोर दस launch भन्दा recipe, instructions, price र repeat use validate भएको एउटा product राम्रो। Momo Achar Masala wider Avaru system को proving ground हो।</p></div></section><section class="brand-principles wrap"><article><span>०१</span><h3>Food-first</h3><p>दाल, मासु, मोमो, अचार, सेकुवाबाट सुरु—“अर्को spice SKU चाहियो” बाट होइन।</p></article><article><span>०२</span><h3>Outcome-led</h3><p>हरेक blend को भान्सामा स्पष्ट काम हुनुपर्छ।</p></article><article><span>०३</span><h3>Nepali-first</h3><p>Language, food references र use cases ग्राहकलाई आफ्नै लाग्नुपर्छ।</p></article><article><span>०४</span><h3>Earn the range</h3><p>Testing ले justify नगरेसम्म future products planned नै रहन्छन्।</p></article></section>` },
    { slug: "products", key: "products", title: "Avaru Masala Range | नेपाली मसला", desc: "Avaru को मसला architecture हेर्नुहोस्: Momo Achar Masala testing मा, र Dal, Masu, Tarkari, Sekuwa, Choila, achar तथा curry blends planned.", h1: "नेपालले पकाउने खानाका लागि focused masala range.", eyebrow: "हाम्रा मसला", body: `<section class="page-hero wrap narrow"><p class="eyebrow">हाम्रा मसला / Our masalas</p><h1>नेपालले पकाउने खानाका लागि focused masala range.</h1><p class="lede">अहिले एउटा product active testing मा छ। तलको wider range ले Avaru कहाँ जाँदैछ देखाउँछ—planned product लाई आजै बिक्रीमा भएको जस्तो देखाउँदैन।</p></section><section class="range-section wrap"><div class="range-groups"><article class="range-group"><div class="range-group-head"><span>०१</span><div><h3>Nepali Favourites</h3></div></div><div class="range-products"><a class="range-product live" href="/ne/products/momo-achar-masala/"><b>Momo Achar Masala</b><small>अहिले testing • SKU #1</small></a><div class="range-product"><b>Sekuwa Masala</b><small>Planned</small></div><div class="range-product"><b>Choila Masala</b><small>Planned</small></div></div></article><article class="range-group"><div class="range-group-head"><span>०२</span><div><h3>Everyday Cooking</h3></div></div><div class="range-products"><div class="range-product priority"><b>Dal Masala</b><small>Priority #2 candidate</small></div><div class="range-product"><b>Masu / Meat Masala</b><small>Priority #3</small></div><div class="range-product"><b>Tarkari Masala</b><small>Priority #4</small></div></div></article><article class="range-group"><div class="range-group-head"><span>०३</span><div><h3>Achar & Quick Solutions</h3></div></div><div class="range-products"><div class="range-product"><b>Achar blends</b><small>Planned signature direction</small></div><div class="range-product"><b>Chicken Curry / Curry Base</b><small>Planned convenience direction</small></div></div></article></div></section>` },
    { slug: "products/momo-achar-masala", key: "product", title: "मोमो अचार मसाला | अवरु", desc: "अवरु मोमो अचार मसाला वीरेन्द्रनगरमा परीक्षण हुँदै गरेको गोलभेँडा र टिमुरको मोमो डुबाउने अचार बनाउन प्रयोग हुने सुक्खा मिश्रण हो।", h1: "मोमो अचार मसाला, सरल रूपमा।", eyebrow: "परीक्षणमा रहेको पहिलो उत्पादन", body: `<section class="page-hero wrap narrow"><p class="eyebrow">परीक्षणमा रहेको पहिलो उत्पादन</p><h1>मोमो अचार मसाला, सरल रूपमा।</h1><p class="lede">यो मोमोसँग दिइने गोलभेँडा र टिमुरको डुबाउने अचार बनाउन प्रयोग हुने सुक्खा मसलाको मिश्रण हो।</p><div class="actions"><a class="button" href="${wa.tester}" target="_blank" rel="noopener">परीक्षणमा सहभागी हुन सोध्नुहोस्</a><a class="text-link" href="#questions">सामान्य प्रश्न पढ्नुहोस्</a></div></section><section class="process wrap"><div class="section-head"><p class="eyebrow">भिन्नता</p><h2>सुक्खा मसला → तयारी → डुबाउने अचार</h2></div><ol class="steps"><li><span>०१</span><strong>मोमो अचार मसाला</strong><p>सुक्खा मसलाको मिश्रण। अवरुको परीक्षण भइरहेको उत्पादन यही हो।</p></li><li><span>०२</span><strong>तयारी</strong><p>गोलभेँडा र टिमुरको अचार बनाउँदा मिश्रण प्रयोग गरिन्छ। अन्तिम विधि स्वीकृत भएको छैन।</p></li><li><span>०३</span><strong>मोमो अचार</strong><p>मोमोसँग दिइने तयार डुबाउने सस। प्याकभित्र बिक्री हुने वस्तु यो होइन।</p></li></ol></section><section class="facts wrap"><div><p class="eyebrow">आजसम्म पक्का</p><h2>अनुमानबिनाका स्पष्ट तथ्य</h2></div><dl><div><dt>उत्पादनको प्रकार</dt><dd>सुक्खा मसलाको मिश्रण</dd></div><div><dt>प्रयोग</dt><dd>गोलभेँडा र टिमुरको मोमो डुबाउने अचार बनाउने</dd></div><div><dt>परीक्षण स्थान</dt><dd>वीरेन्द्रनगर, सुर्खेत, नेपाल</dd></div><div><dt>अझै अन्तिम हुँदै</dt><dd>रेसिपी, विधि, प्याकको आकार, मूल्य, उपलब्धता र सार्वजनिक हुने मिति</dd></div></dl></section><section class="faq wrap narrow" id="questions"><p class="eyebrow">सामान्य प्रश्न</p><h2>सिधा उत्तर</h2><details open><summary>मोमो अचार मसाला के हो?</summary><p>यो मोमोसँग दिइने गोलभेँडा र टिमुरको डुबाउने अचार बनाउँदा प्रयोग हुने सुक्खा मसलाको मिश्रण हो।</p></details><details><summary>के यो खान तयार अचार हो?</summary><p>होइन। मसाला अचार बनाउन प्रयोग गरिने सामग्री हो; यो खान तयार सस होइन।</p></details><details><summary>के यो मोमोको भराइमा हालिन्छ?</summary><p>होइन। यो मोमोको भित्रको भराइका लागि होइन, डुबाउने अचारका लागि हो।</p></details><details><summary>के अहिले किन्न पाइन्छ?</summary><p>व्यापारिक विवरण स्वीकृत भएका छैनन्। उत्पादन अहिले वीरेन्द्रनगरमा परीक्षण हुँदैछ।</p></details><details><summary>परीक्षणमा कसरी सहभागी हुने?</summary><p>अवरुलाई WhatsApp सन्देश पठाउनुहोस्। अहिलेको परीक्षण चरण तपाईंका लागि उपयुक्त भए/नभएको जानकारी दिनेछौँ।</p></details></section>` },
    { slug: "testing", key: "testing", title: "उत्पादन परीक्षणमा सहभागी हुनुहोस् | अवरु", desc: "वीरेन्द्रनगरमा अवरु मोमो अचार मसाला परीक्षण गर्न चाहनुहुन्छ? WhatsApp मा आफ्नो रुचि पठाउनुहोस्।", h1: "पकाउनुहोस्। चाख्नुहोस्। के काम गर्‍यो भन्नुहोस्।", eyebrow: "परीक्षणमा सहभागी हुनुहोस्", body: `<section class="page-hero wrap narrow"><p class="eyebrow">परीक्षणमा सहभागी हुनुहोस्</p><h1>पकाउनुहोस्। चाख्नुहोस्। के काम गर्‍यो भन्नुहोस्।</h1><p class="lede">व्यापारिक विवरण अन्तिम हुनुअघि अवरु मोमो अचार मसाला परीक्षण गर्न वीरेन्द्रनगर र वरपरका इच्छुक घरका भान्सेलाई आमन्त्रण गर्दैछौँ।</p></section><section class="testing-grid wrap"><div><h2>परीक्षण भनेको के हो</h2><ol class="number-list"><li><span>१</span><p><strong>आफ्नो रुचि बताउनुहोस्।</strong><br>तलको बटनबाट छोटो WhatsApp कुराकानी सुरु गर्नुहोस्।</p></li><li><span>२</span><p><strong>हामी उपयुक्तता पुष्टि गर्छौँ।</strong><br>अवसर स्थान र परीक्षणको हालको चरणमा निर्भर हुन सक्छ।</p></li><li><span>३</span><p><strong>बनाएर प्रतिक्रिया दिनुहोस्।</strong><br>स्पष्टता, तयारी र तपाईंले पस्कन चाहने नतिजाबारे इमानदार टिप्पणी चाहन्छौँ।</p></li></ol></div><aside class="contact-card"><p class="eyebrow">WhatsApp बाट सुरु गर्नुहोस्</p><h2>परीक्षण गर्न इच्छुक हुनुहुन्छ?</h2><p>लिङ्कले पहिल्यै लेखिएको सन्देश खोल्छ। WhatsApp ले तपाईंको फोन नम्बर र तपाईंले पठाउन रोजेको जानकारी सिधै अवरुसँग बाँड्छ।</p><a class="button button-dark" href="${wa.tester}" target="_blank" rel="noopener">अवरुलाई सन्देश पठाउनुहोस्</a><p class="micro">वेबसाइट फारम वा लुकेको तथ्याङ्क सङ्कलन छैन।</p></aside></section>` },
    { slug: "contact", key: "contact", title: "अवरुलाई सम्पर्क गर्नुहोस् | परीक्षण र खुद्रा विक्रेता सोधपुछ", desc: "उत्पादन परीक्षण, खुद्रा विक्रेता कुराकानी वा सामान्य प्रश्नका लागि अवरुलाई WhatsApp मा सम्पर्क गर्नुहोस्।", h1: "एउटा नम्बर, तीन स्पष्ट कुराकानी।", eyebrow: "अवरुलाई सम्पर्क", body: `<section class="page-hero wrap narrow"><p class="eyebrow">अवरुलाई सम्पर्क</p><h1>एउटा नम्बर, तीन स्पष्ट कुराकानी।</h1><p class="lede">सन्देशको कारण छान्नुहोस् र WhatsApp सही परिचयसहित खुल्छ। हामी अहिले वीरेन्द्रनगर, सुर्खेत, नेपालमा परीक्षण गर्दैछौँ।</p></section><section class="contact-options wrap"><article><span>०१</span><h2>घरका भान्से</h2><p>मोमो अचार मसाला परीक्षणमा सहभागी हुनेबारे सोध्नुहोस्।</p><a class="text-link" href="${wa.tester}" target="_blank" rel="noopener">उत्पादन परीक्षणमा सहभागी हुनुहोस्</a></article><article><span>०२</span><h2>खुद्रा विक्रेता</h2><p>भविष्यमा अवरु राख्ने सम्भावनाबारे कुराकानी सुरु गर्नुहोस्। उपलब्धता पक्का छैन।</p><a class="text-link" href="${wa.retailer}" target="_blank" rel="noopener">खुद्रा विक्रेता सोधपुछ</a></article><article><span>०३</span><h2>सामान्य प्रश्न</h2><p>अवरु वा परीक्षणमा रहेको उत्पादनबारे अरू कुरा सोध्नुहोस्।</p><a class="text-link" href="${wa.general}" target="_blank" rel="noopener">सामान्य सोधपुछ पठाउनुहोस्</a></article></section><section class="banner"><div class="wrap"><p class="eyebrow">WhatsApp</p><h2>+977 9822403262</h2><p>हामीले कार्यालयको ठेगाना, इमेल वा खुल्ने समय सार्वजनिक गरेका छैनौँ।</p></div></section>` }
  ]
};

function pairedPath(locale, slug) { return `${copy[locale].switchPrefix}${slug ? `/${slug}` : ""}/`.replace("//", "/"); }
function pagePath(locale, slug) { return `${copy[locale].prefix}${slug ? `/${slug}` : ""}/`.replace("//", "/"); }
function nav(locale, key) { const c = copy[locale]; return c.nav.map(([label, href]) => `<a href="${href}"${(key === "home" && href === (locale === "en" ? "/" : "/ne/")) || href.includes(`/${key}/`) ? ' aria-current="page"' : ""}>${label}</a>`).join(""); }
function schema(page, locale) {
  const organization = {"@context":"https://schema.org","@type":"Organization","name":"Avaru","description": locale === "en" ? "A masala and spices brand being developed for Nepali kitchens." : "नेपाली भान्साका लागि विकास हुँदै गरेको मसला ब्रान्ड।","areaServed":{"@type":"Place","name":"Birendranagar, Surkhet, Nepal"},"contactPoint":{"@type":"ContactPoint","telephone":"+9779822403262","contactType":"customer service","availableLanguage":["English","Nepali"]}};
  if (page.key === "product") return [organization,{"@context":"https://schema.org","@type":"Product","name":locale === "en" ? "Avaru Momo Achar Masala" : "अवरु मोमो अचार मसाला","brand":{"@type":"Brand","name":"Avaru"},"category":"Dry spice blend","description":page.desc}];
  return organization;
}
function render(page, locale) {
  const c = copy[locale], canonical = `${origin}${pagePath(locale, page.slug)}`;
  const alternate = `${origin}${pairedPath(locale, page.slug)}`;
  return `<!doctype html><html lang="${c.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.desc}"><meta name="robots" content="noindex,nofollow"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="${locale}" href="${canonical}"><link rel="alternate" hreflang="${locale === "en" ? "ne" : "en"}" href="${alternate}"><link rel="alternate" hreflang="x-default" href="${origin}/${page.slug ? `${page.slug}/` : ""}"><meta property="og:type" content="website"><meta property="og:site_name" content="Avaru"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.desc}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}/assets/og-avaru.png"><meta property="og:image:alt" content="Avaru — Masalas for Nepali kitchens, shown with momo and dipping achar"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${page.title}"><meta name="twitter:description" content="${page.desc}"><meta name="twitter:image" content="${origin}/assets/og-avaru.png"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${JSON.stringify(schema(page, locale)).replaceAll("<", "\\u003c")}</script></head><body><a class="skip" href="#main">${c.skip}</a><div class="preview-bar">${c.private}</div><header class="site-header"><a class="brand" href="${c.prefix || "/"}" aria-label="Avaru home">Avaru<span>अवरु</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span>${c.menu}</span><i aria-hidden="true"></i></button><nav id="site-nav" aria-label="Primary navigation">${nav(locale, page.key)}</nav><a class="lang" href="${pairedPath(locale, page.slug)}" hreflang="${locale === "en" ? "ne" : "en"}">${c.switchLabel}</a></header><main id="main">${page.body}</main><footer><div class="wrap footer-grid"><div><a class="brand brand-light" href="${c.prefix || "/"}">Avaru<span>अवरु</span></a><p>${c.footer}</p></div><div><p class="footer-label">${locale === "en" ? "Currently" : "अहिले"}</p><p>${c.location}</p></div><div><p class="footer-label">${locale === "en" ? "Talk to us" : "सम्पर्क"}</p><a href="${wa.general}" target="_blank" rel="noopener">WhatsApp +977 9822403262</a></div></div><div class="wrap footer-bottom"><span>© 2026 Avaru</span><span>${locale === "en" ? "No social accounts published yet." : "सामाजिक सञ्जाल खाता अझै सार्वजनिक छैन।"}</span></div></footer><script src="/assets/site.js" defer></script></body></html>`;
}

await rm(dist, {recursive:true, force:true});
await mkdir(path.join(dist, "assets"), {recursive:true});
for (const locale of ["en","ne"]) for (const page of pages[locale]) {
  const dir = path.join(dist, pagePath(locale, page.slug));
  await mkdir(dir, {recursive:true});
  await writeFile(path.join(dir, "index.html"), render(page, locale));
}
await cp(path.join(root,"src","assets"), path.join(dist,"assets"), {recursive:true});
await cp(path.join(root,"src","site.css"), path.join(dist,"assets","site.css"));
await cp(path.join(root,"src","site.js"), path.join(dist,"assets","site.js"));
await cp(path.join(root,"src","favicon.svg"), path.join(dist,"favicon.svg"));
const urls = pages.en.flatMap(p => [`${origin}${pagePath("en",p.slug)}`,`${origin}${pagePath("ne",p.slug)}`]);
await writeFile(path.join(dist,"sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join("")}</urlset>`);
await writeFile(path.join(dist,"robots.txt"), "User-agent: *\nDisallow: /\n# Private preview. Enable indexing only after a public domain is approved.\n");
console.log(`Built ${urls.length} localized pages in ${dist}`);
